version: '2'

services:
  docker-slapd:
    container_name: docker-slapd
    restart: always
    image: octbr.ine/docker-slapd:0.4.6
    environment: 
    - LDAP_DOMAIN=
    - LDAP_ORGNAME=
    - LDAP_ORGNAME_DESC=
    - LDAP_PEOPLE=
    - LDAP_PEOPLE_DESC=
    - LDAP_GROUP=
    - LDAP_GROUP_DESC=

    - LDAP_MANAGER_NAME=
    - LDAP_MANAGER_PASS=

    - LDAP_DATABASE=
    - LDAP_LOGLEVEL=

    - SLAPD_DEBUGLEVEL=
    - SLAPD_LDAP=
    - SLAPD_LDAPI=
    - SLAPD_LDAPS=

    - CA_PEM_FILE=
    - SERVER_PEM_FILE=

    - CERT_CA_CN=
    - CERT_CA_O=
    - CERT_CA_C=
    - CERT_SV_CN=
    - NSSDB_PASSWORD=
    - NSSDB_CACERT_NAME=
    - NSSDB_CERT_NAME=

    volumes:
    - /srv/docker-slapd/openldap
