version: '2'

services:
  centos-ldap:
    container_name: docker-ldap
    restart: always
    image: octbr.ine/docker-ldap:0.1
    environment: 
    - LDAP_DOMAIN=
    - LDAP_ORGNAME=
    - LDAP_ORGNAME_DESC=
    - LDAP_PEOPLE=
    - LDAP_PEOPLE_DESC=
    - LDAP_GROUP=
    - LDAP_GROUP_DESC=

    - LDAP_MANAGER_NAME=
    - LDAP_MANAGER_PASS=
    - LDAP_MANAGER_DOMAIN=
